name:                hs2md
version:             0.6.0.0
github:              "nobsun/hs2md.git"
license:             BSD3
author:              "Nobuo Yamasita"
maintainer:          "nobsun@sampou.org"
copyright:           "2020 Nobuo Yamshita"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/nobsun/hs2md#readme>

dependencies:
- base >= 4.7 && < 5
- text
- filepath
- exceptions
- directory

ghc-options:
- -O2

library:
  source-dirs: src

executables:
  mkdocdir:
    main:               Main.hs
    source-dirs:        app/mkdocdir
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs2md

  mkmds:
    main:               Main.hs
    source-dirs:        app/mkmds
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs2md

  md2hs:
    main:               Main.hs
    source-dirs:        app/md2hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs2md

  hs2md:
    main:               Main.hs
    source-dirs:        app/hs2md
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs2md
