name:                hs2md
version:             0.6.0.0
github:              "nobsun/hs2md.git"
license:             BSD3
author:              "Nobuo Yamasita"
maintainer:          "nobsun@sampou.org"
copyright:           "2020 Nobuo Yamshita"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/nobsun/hs2md#readme>

dependencies:
- base >= 4.7 && < 5
- text
- filepath
- exceptions
- directory

ghc-options:
- -O2

library:
  source-dirs: src

executables:
  hs2md:
    main:                hs2md.hs
    source-dirs:         app
    dependencies:
    - hs2md

  md2hs:
    main:                md2hs.hs
    source-dirs:         app
    dependencies:
    - hs2md

  mkmds:
    main:		mkmds.hs
    source-dirs:	app
    dependencies:
    - hs2md

  mkdocdir:
    main:		mkdocdir.hs
    source-dirs:	app
    dependencies:
    - hs2md